### ISSUE TITLE
Use the Python package manager infrastructure

### ISSUE THREAD

**Issue by JeroenDeDauw** [FAForever/fafbot#8]
This repository appears to mostly contain dependencies for the actual FAFbot, in the form of copied code. This is problematic in several ways, amongst which:

* It is not entirely obvious what code is external and what is part of FAFbot
* It is not easy to tell if there are modifications to the external code that we made and require
* It is not obvious which versions of the external code are used
* It is harder to upgrade the external code

Not being familiar with this code and not having done Python in a long time, it seems to me that these are external code:

* ircbot.py (rather obvious this one)
* the whole trueSkill directory
* the whole irc directory (I'm guessing, and hoping, this is a library)

An additional problem is that the required version of Python and any additional system dependencies are not specified anywhere. That problem can also be solved by adding this information to the README, as per #5

**Comment by JeroenDeDauw** [comment]
Started using package manager in https://github.com/FAForever/fafbot/pull/11

Removed trueSkill in https://github.com/FAForever/fafbot/pull/14

Removed ircbot.py in https://github.com/FAForever/fafbot/pull/13

**Comment by Sheeo** [comment]
:+1:

**Comment by Sheeo** [comment]
If you reference the issue from a commit with "Fixes" or "Closes", it will automatically get closed when the commit hits master
